### ISSUE TITLE
Direct APK Download

### ISSUE THREAD

**Issue by kench** [rpi-mobile/RPIMobile-Android#3]
Android devices without the Google Play Store exist.  Providing an APK download link would be useful for RPI students who own them.

**Comment by pdpiech** [comment]
The flaw in that argument resides in the fact that, in order to display the Campus Map, the latest version requires Google Play Services and Google Service Framework installed on the device which are also required by the Google Play Store.  If anyone has any thoughts on this, please comment before I close this issue.

**Comment by nvsio** [comment]
It also doesn't make sense for us to manage distribution of .apk outside of the Google Play Store. Students using devices without the Play Store are welcome to compile the .apk from source.
